export interface Category {
  key: string;
  en: string;
  bn: string;
  iconName?: string;
  count?: number;
}

export interface ProductVariant {
  k: string;
  en: string;
  bn: string;
  price: number;
}

export interface Product {
  id: string;
  cat: "bags" | "home" | "table" | "office" | "gifts" | "footwear" | "jewelry";
  slug: string;
  en: string;
  bn: string;
  taglineEn: string;
  taglineBn: string;
  descriptionEn: string;
  descriptionBn: string;
  storyEn: string;
  storyBn: string;
  featuresEn: string[];
  featuresBn: string[];
  dimensionsEn: string;
  dimensionsBn: string;
  materialEn: string;
  materialBn: string;
  careEn: string[];
  careBn: string[];
  primaryImage: string;
  images: string[];
  variants: ProductVariant[];
  badge?: {
    text: string;
    textEn: string;
    variant: "eco" | "sale" | "handmade" | "neutral";
  };
  isBestseller?: boolean;
  isFeatured?: boolean;
  inStock?: boolean;
  rating?: number;
  reviewsCount?: number;
}

export const CATEGORIES: Category[] = [
  { key: "bags", en: "Bags & Totes", bn: "ব্যাগ ও টোট", count: 6 },
  { key: "jewelry", en: "Jewelry & Accessories", bn: "গহনা ও অলঙ্কার", count: 2 },
  { key: "home", en: "Home & Living", bn: "হোম ও লিভিং", count: 5 },
  { key: "table", en: "Kitchen & Dining", bn: "কিচেন ও ডাইনিং", count: 4 },
  { key: "office", en: "Office & Stationery", bn: "অফিস ও স্টেশনারি", count: 2 },
  { key: "gifts", en: "Gift Boxes & Hampers", bn: "গিফট ও হ্যাম্পার", count: 2 },
  { key: "footwear", en: "Eco Footwear", bn: "ইকো ফুটওয়্যার", count: 1 },
];

export const PRODUCTS: Product[] = [
  {
    id: "P00",
    cat: "bags",
    slug: "handcrafted-jute-clutch-wallet",
    en: "Handcrafted Jute Clutch Wallet & Pouch",
    bn: "হাতে বোনা পাটের ক্ল্যাচ ওয়ালেট ও ছোট পার্স",
    taglineEn: "Pocket-friendly artisanal elegance in pure mustard jute canvas",
    taglineBn: "সরিষা-হলুদ পাটের আভিজাত্য · ওয়াটারপ্রুফ ফিনিশিং ও ভ্যালক্রো ফ্ল্যাপ",
    descriptionEn: "A charming, ultra-lightweight women's clutch wallet meticulously crafted from pure mustard-yellow jute canvas with contrast charcoal border piping. Features a protective water-repellent rubber lining, secure Velcro flap closure, and a compact silhouette perfectly sized for cash, cards, keys, and cosmetics.",
    descriptionBn: "মানিকগঞ্জের নারী কারিগরদের হাতে তৈরি প্রিমিয়াম সরিষা-হলুদ রঙের পাটের ক্ল্যাচ ওয়ালেট ও পার্স। চারপাশে আকর্ষণীয় ডার্ক চারকোল পাইপিং বর্ডার ও ডাবল স্টিচ ফিনিশিং। ভেতরে ওয়াটারপ্রুফ রাবার স্তর থাকায় টাকা-পয়সা ও প্রসাধন সামগ্রী পানিতে ভেজে না। ভ্যালক্রো ফ্ল্যাপ থাকায় সহজে খোলা ও বন্ধ করা যায়।",
    storyEn: "Engineered from a single 13\" x 9\" unfolded pattern sheet. Hand-stitched with precision at the Paatbari artisan hub in Manikganj.",
    storyBn: "১৩\" × ৯\" সাইজের একটি নিখুঁত প্যানেল থেকে গ্রামীণ নারী কারিগরদের পরম যত্নে তৈরি। ফেয়ার-ট্রেড পারিশ্রমিক ও শতভাগ প্লাস্টিকমুক্ত।",
    featuresEn: [
      "100% natural mustard-yellow textured jute canvas",
      "Reinforced charcoal piping trim with double-stitch perimeter",
      "Hidden water-repellent rubber backing to protect inner items",
      "Quick-snap Velcro closure designed for everyday effortless use",
      "Direct artisan pricing matching our transparent ELI5 costing model",
    ],
    featuresBn: [
      "১০০% প্রাকৃতিক সরিষা-হলুদ টেক্সচার্ড খাঁটি জুট ক্যানভাস",
      "চারপাশে মজবুত চারকোল পাইপিং বর্ডার ও নিখুঁত ডাবল সেলাই",
      "ভেতরে ওয়াটারপ্রুফ রাবার ব্যাক স্তর যা জিনিসপত্র শুকনো রাখে",
      "সহজে খোলা ও লাগানোর সুবিধাজনক ভ্যালক্রো ফ্ল্যাপ ক্লিপ",
      "আমাদের উন্মুক্ত ELI5 কস্টিং মডেলের শতভাগ স্বচ্ছ সাশ্রয়ী মূল্য",
    ],
    dimensionsEn: "9\" W x 4.5\" H x 1\" D (Unfolded: 13\" x 9\")",
    dimensionsBn: "৯\" চওড়া × ৪.৫\" উচ্চতা × ১\" গভীরতা (আনফোল্ডেড: ১৩\" × ৯\")",
    materialEn: "Natural Mustard Jute Canvas, Rubber Coating & Charcoal Piping",
    materialBn: "প্রাকৃতিক সরিষা-হলুদ জুট ক্যানভাস, রাবার কোটিং ও চারকোল পাইপিং",
    careEn: ["Gently wipe with dry or lightly damp cloth", "Air dry in shade", "Do not soak in water"],
    careBn: ["শুকনো বা হালকা ভেজা নরম কাপড় দিয়ে মুছে নিন", "ছায়ায় শুকিয়ে নিন", "পানিতে সম্পূর্ণ নিমজ্জিত করবেন না"],
    primaryImage: "/images/products/jute-clutch-wallet-studio.jpg",
    images: ["/images/products/jute-clutch-wallet-studio.jpg", "/images/products/jute-clutch-wallet-real.jpg"],
    badge: { text: "স্বচ্ছ কস্টিং ৳৫৫", textEn: "Fair Price ৳55", variant: "eco" },
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 38,
    variants: [
      { k: "mustard", en: "Mustard Ochre", bn: "সরিষা হলুদ", price: 55 },
      { k: "trio", en: "Set of 3 (Gift Pack)", bn: "৩টির গিফট সেট", price: 150 },
    ],
  },
  {
    id: "P01",
    cat: "bags",
    slug: "classic-jute-tote-bag",
    en: "Classic Handcrafted Jute Tote Bag",
    bn: "ক্লাসিক পাটের টোট ব্যাগ",
    taglineEn: "Timeless style meets 100% natural golden fibre durability",
    taglineBn: "প্রকৃতি ও আভিজাত্যের অপূর্ব মেলবন্ধন · ১০০% খাঁটি পাট",
    descriptionEn: "Our flagship Classic Jute Tote Bag is meticulously hand-woven from Grade-A premium natural golden jute fibres. Engineered with dual-reinforced cotton rope handles, inner spill-resistant natural lining, and high-tensile stress stitching, it comfortably carries up to 10kg with effortless elegance.",
    descriptionBn: "পাটবাড়ির সিগনেচার ক্লাসিক টোট ব্যাগটি ১০০% গ্রেড-এ প্রাকৃতিক সোনালি পাটের সুতোয় হাতে বোনা। আরামদায়ক ডাবল-রিইনফোর্সড কটন রোপ হ্যান্ডেল, ভেতরে মসৃণ লাইনিং এবং মজবুত সেলাই এটিকে ১০ কেজি পর্যন্ত ভারবহনে নির্ভরযোগ্য ও অত্যন্ত আকর্ষণীয় করে তুলেছে।",
    storyEn: "Crafted by rural women artisans in Manikganj Sadar using ancestral weaving looms. Each tote takes approximately 8 hours of patient braiding and hand-stitching.",
    storyBn: "মানিকগঞ্জ সদরের গ্রামীণ নারী কারিগরদের দক্ষ হাতে তৈরি। প্রতিটি ব্যাগ বুনতে প্রায় ৮ ঘণ্টার নিখুঁত শ্রম ও ভালোবাসা প্রয়োজন হয়।",
    featuresEn: [
      "100% Biodegradable & zero-plastic design",
      "Reinforced heavy-duty cotton rope handles (11 inch drop)",
      "Inner magnetic clasp & quick-access pocket for phone/keys",
      "Stress-tested to comfortably hold up to 10 kg",
    ],
    featuresBn: [
      "১০০% বায়োডিগ্রেডেবল ও প্লাস্টিকমুক্ত পরিবেশবান্ধব পণ্য",
      "আরামদায়ক ও শক্তিশালী কটন রোপ হ্যান্ডেল (১১ ইঞ্চি ড্রপ)",
      "মোবাইল ও চাবি রাখার জন্য ভেতরের পকেট ও ম্যাগনেটিক ক্লিপ",
      "১০ কেজি পর্যন্ত ভারবহনে পরীক্ষিত ও দীর্ঘস্থায়ী",
    ],
    dimensionsEn: "15\" W x 14\" H x 5\" D (Handle Drop: 11\")",
    dimensionsBn: "১৫\" চওড়া × ১৪\" উচ্চতা × ৫\" গভীরতা (হাতল: ১১\")",
    materialEn: "100% Natural Golden Jute with Organic Cotton Rope Handles",
    materialBn: "১০০% প্রাকৃতিক সোনালি পাট ও জৈব সুতি রোপ হ্যান্ডেল",
    careEn: ["Spot clean with a damp cloth", "Air dry naturally in shade", "Do not machine wash or soak"],
    careBn: ["হালকা ভেজা কাপড় দিয়ে আলতো করে মুছে নিন", "ছায়াযুক্ত বাতাসে শুকিয়ে নিন", "মেশিন ওয়াশ বা পানিতে ভিজিয়ে রাখবেন না"],
    primaryImage: "/images/products/classic-tote.jpg",
    images: ["/images/products/classic-tote.jpg", "/images/products/shopping-bag.jpg", "/images/artisan/artisan-loom.jpg"],
    badge: { text: "বেস্টসেলার", textEn: "Bestseller", variant: "handmade" },
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 128,
    variants: [
      { k: "natural", en: "Natural Golden", bn: "ন্যাচারাল সোনালি", price: 450 },
      { k: "dyed", en: "Dyed Forest Green", bn: "রঙিন (গাঢ় সবুজ)", price: 480 },
    ],
  },
  {
    id: "P02",
    cat: "bags",
    slug: "jute-laptop-bag",
    en: "Executive Padded Jute Laptop Bag 15.6\"",
    bn: "পাটের ল্যাপটপ ব্যাগ ১৫.৬\"",
    taglineEn: "Sustainable executive messenger with shockproof fleece cushioning",
    taglineBn: "১৫.৬ ইঞ্চি ল্যাপটপের শকপ্রুফ প্যাডেড এক্সিকিউটিভ ব্যাগ",
    descriptionEn: "Designed for modern eco-conscious professionals, this executive laptop bag combines high-density woven jute canvas with vegetable-tanned genuine leather trim. Features an ultra-soft fleece padded interior compartment holding laptops up to 15.6\", dedicated charger & notebook sleeves, and an adjustable shoulder strap.",
    descriptionBn: "আধুনিক পেশাদারদের জন্য তৈরি এক্সিকিউটিভ পাটের ল্যাপটপ ব্যাগ। টেকসই জুট ক্যানভাস ও ন্যাচারাল লেদার ফিনিশিং সমন্বিত। ভেতরে সফট শকপ্রুফ প্যাডেড কুশনিং যা ১৫.৬ ইঞ্চি পর্যন্ত ল্যাপটপকে নিরাপদ রাখে। সাথে রয়েছে চার্জার, মাউস ও ডায়েরি রাখার সুসজ্জিত চেম্বার।",
    storyEn: "Crafted at the Paatbari Manikganj workshop with precision brass hardware and eco-certified organic lining.",
    storyBn: "পাটবাড়ির মানিকগঞ্জ উৎপাদন কেন্দ্রে দক্ষ কারিগরদের হাতে নিখুঁত মেটালিক ব্রাস ফিটিংস সহ প্রস্তুত।",
    featuresEn: [
      "High-density 360° impact protective laptop sleeve",
      "Detachable & adjustable padded shoulder strap with brass clasps",
      "Dedicated multi-compartment organizers for charger, pens & phone",
      "Water-resistant interior cotton lining",
    ],
    featuresBn: [
      "৩৬০° শক-প্রটেক্টিভ প্যাডেড ল্যাপটপ কম্পার্টমেন্ট",
      "খুলনযোগ্য ও অ্যাডজাস্টেবল প্যাডেড শোল্ডার বেল্ট",
      "চার্জার, পেন ও মোবাইল রাখার জন্য আলাদা অভ্যন্তরীণ পকেট",
      "পানি প্রতিরোধক মসৃণ অভ্যন্তরীণ সুতি লাইনিং",
    ],
    dimensionsEn: "16.5\" W x 12\" H x 3.5\" D (Fits up to 15.6\" Laptops)",
    dimensionsBn: "১৬.৫\" চওড়া × ১২\" উচ্চতা × ৩.৫\" গভীরতা (১৫.৬ ইঞ্চি পর্যন্ত ল্যাপটপ)",
    materialEn: "Premium Jute Canvas, Vegetable-Tanned Saddle Leather, Brass Hardware",
    materialBn: "প্রিমিয়াম জুট ক্যানভাস, জেনুইন স্যাডেল লেদার ট্রিম, মেটালিক ব্রাস",
    careEn: ["Wipe clean with a damp microfiber cloth", "Condition leather accents with wax occasionally"],
    careBn: ["মাইক্রোফাইবার হালকা ভেজা কাপড় দিয়ে পরিষ্কার করুন", "লেদার অংশে মাঝে মাঝে সামান্য মোম পলিশ করতে পারেন"],
    primaryImage: "/images/products/laptop-bag.jpg",
    images: ["/images/products/laptop-bag.jpg", "/images/products/file-folder.jpg", "/images/artisan/artisan-loom.jpg"],
    badge: { text: "প্রিমিয়াম", textEn: "Executive", variant: "neutral" },
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    rating: 4.8,
    reviewsCount: 84,
    variants: [
      { k: "std", en: "Standard 15.6\"", bn: "স্ট্যান্ডার্ড ১৫.৬ ইঞ্চি", price: 1450 },
    ],
  },
  {
    id: "P03",
    cat: "bags",
    slug: "ladies-jute-handbag",
    en: "Artisanal Ladies Jute Shoulder Handbag",
    bn: "লেডিস পাটের হ্যান্ডব্যাগ",
    taglineEn: "Sophisticated everyday luxury woven from pure artisanal jute",
    taglineBn: "আভিজাত্য ও প্রকৃতির অপূর্ব মেলবন্ধন · ফ্যাশনেবল শোল্ডার ব্যাগ",
    descriptionEn: "An epitome of understated luxury, this ladies handbag features a structured silhouette hand-woven from fine-count golden jute fibers accented with smooth tan leatherette handles. A brass zippered closure keeps all your daily essentials secure while turning heads with organic elegance.",
    descriptionBn: "নারীদের রুচিশীল ব্যক্তিত্বের সাথে মানানসই আধুনিক পাটের শোল্ডার হ্যান্ডব্যাগ। খাঁটি পাটের নিখুঁত সূক্ষ্ম বুনন এবং বাদামি লেদার হ্যান্ডেলের অপূর্ব যুগলবন্দি। ভেতরে পর্যাপ্ত জায়গা ও জিপার পকেট দৈনন্দিন ব্যবহারে এনে দেয় আভিজাত্য।",
    storyEn: "Handmade by our women's cooperative in Manikganj, championing fair wages and zero synthetic waste.",
    storyBn: "মানিকগঞ্জের নারী তাঁতশিল্পীদের দ্বারা স্বহস্তে নির্মিত, যা গ্রামীণ নারীদের অর্থনৈতিক ক্ষমতায়নের প্রতীক।",
    featuresEn: [
      "Elegant curved designer silhouette with flat structured base",
      "Full top zippered security closure with smooth gliding zip",
      "Dual interior slip pockets plus one zipped coin pocket",
      "Ultra-lightweight yet remarkably robust",
    ],
    featuresBn: [
      "আধুনিক কার্ভড ডিজাইনার শেইপ ও ফ্ল্যাট বটম",
      "নিরাপদ টপ মেটালিক জিপার ক্লোজার",
      "ভেতরে মোবাইল ও কয়েন রাখার জন্য জিপার পকেট",
      "ওজনে হালকা কিন্তু অত্যন্ত মজবুত ও টেকসই",
    ],
    dimensionsEn: "13.5\" W x 10.5\" H x 4.5\" D",
    dimensionsBn: "১৩.৫\" চওড়া × ১০.৫\" উচ্চতা × ৪.৫\" গভীরতা",
    materialEn: "Fine-Woven Jute Fibres with Tan Saddle Trims",
    materialBn: "সূক্ষ্ম বুননের খাঁটি সোনালি পাট ও স্যাডেল লেদার ট্রিম",
    careEn: ["Gentle dry brushing or spot wipe", "Store with stuffing to maintain shape"],
    careBn: ["শুকনো নরম ব্রাশ দিয়ে পরিষ্কার করুন", "শেপ ঠিক রাখতে ভেতরে পেপার রেখে সংরক্ষণ করুন"],
    primaryImage: "/images/products/ladies-handbag.jpg",
    images: ["/images/products/ladies-handbag.jpg", "/images/products/classic-tote.jpg"],
    badge: { text: "নতুন ডিজাইন", textEn: "New Design", variant: "handmade" },
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 92,
    variants: [
      { k: "std", en: "Classic Tan", bn: "ক্লাসিক ট্যান", price: 950 },
    ],
  },
  {
    id: "P04",
    cat: "bags",
    slug: "large-jute-shopping-bag",
    en: "Heavy-Duty Large Jute Market Shopper",
    bn: "বড় পাটের বাজারের ব্যাগ",
    taglineEn: "Replace 1,000+ plastic bags with reinforced bamboo cane handles",
    taglineBn: "বাঁশের হাতলযুক্ত মজবুত বাজারের ব্যাগ · প্লাস্টিকের সেরা বিকল্প",
    descriptionEn: "Built for heavy market days, grocery trips, and weekend farmers' markets, this large jute shopper features rigid round bamboo cane handles and cross-stitched gussets capable of bearing up to 15kg without straining.",
    descriptionBn: "দৈনন্দিন বাজার ও গ্রোসারি শপিংয়ের জন্য তৈরি হেভি-ডিউটি পাটের ব্যাগ। মজবুত গোলাকার বাঁশের হাতল এবং অতিরিক্ত লোড ধারণক্ষমতা সম্পন্ন। ১৫ কেজি পর্যন্ত ভার অনায়াসে বহন করতে পারে। প্লাস্টিক ব্যাগের সেরা টেকসই বিকল্প।",
    storyEn: "Crafted using unbleached raw jute yarns, sun-dried and hand-bound by traditional artisans in Manikganj.",
    storyBn: "মানিকগঞ্জের ঐতিহ্যবাহী কারিগরদের দ্বারা রোদে শুকানো খাঁটি পাট ও বাঁশ দিয়ে হাতে তৈরি।",
    featuresEn: [
      "Solid circular polished bamboo cane carrying handles",
      "Wide flat gusset base for freestanding stability while loading",
      "Carries up to 15 kg of groceries, vegetables, and household goods",
      "100% biodegradable and zero harmful microplastics",
    ],
    featuresBn: [
      "মজবুত পালিশ করা বাঁশের গোলাকার আরামদায়ক হাতল",
      "চওড়া তলা যা মেঝেতে নিজে থেকেই সোজা হয়ে দাঁড়িয়ে থাকে",
      "১৫ কেজি পর্যন্ত ওজনের শাকসবজি ও বাজার বহনে সক্ষম",
      "শতভাগ পরিবেশবান্ধব ও প্লাস্টিকমুক্ত",
    ],
    dimensionsEn: "17\" W x 15\" H x 7\" Gusset",
    dimensionsBn: "১৭\" চওড়া × ১৫\" উচ্চতা × ৭\" তলা",
    materialEn: "Raw Golden Jute & Natural Treated Bamboo Cane",
    materialBn: "খাঁটি সোনালি পাট ও প্রাকৃতিক বাঁশের হাতল",
    careEn: ["Brush off dust regularly", "Air dry if exposed to moisture"],
    careBn: ["নিয়মিত শুকনো কাপড় দিয়ে ঝেড়ে নিন", "ভিজে গেলে বাতাসে ভালো করে শুকিয়ে নিন"],
    primaryImage: "/images/products/shopping-bag.jpg",
    images: ["/images/products/shopping-bag.jpg", "/images/products/classic-tote.jpg"],
    badge: { text: "টেকসই", textEn: "Heavy Duty", variant: "eco" },
    inStock: true,
    rating: 4.8,
    reviewsCount: 71,
    variants: [
      { k: "std", en: "Large (17x15\")", bn: "বড় সাইজ (১৭×১৫\")", price: 380 },
    ],
  },
  {
    id: "P05",
    cat: "bags",
    slug: "travel-backpack",
    en: "Handcrafted Jute Heritage Travel Backpack",
    bn: "পাটের ট্রাভেল ও ডেপ্যাক ব্যাকপ্যাক",
    taglineEn: "Rustic wanderlust meets ergonomic functionality and leather buckles",
    taglineBn: "লেদার বাকলযুক্ত বিলাসবহুল পাটের ট্রাভেল ব্যাকপ্যাক",
    descriptionEn: "The ultimate conversation piece for conscious explorers. Crafted from tight-weave golden jute canvas, genuine antique-finish leather strapping, and brass roller buckles. Includes a drawstring main cavity, quick-access front flap pocket, and ergonomic padded shoulder straps.",
    descriptionBn: "পরিবেশসচেতন ভ্রমণপিপাসুদের জন্য তৈরি বিলাসবহুল পাটের ব্যাকপ্যাক। ঘন বুননের সোনালি জুট ক্যানভাস, অ্যান্টিক লেদার স্ট্র্যাপ ও ব্রাস বাকল দিয়ে সজ্জিত। ড্র-স্ট্রিং মেইন কম্পার্টমেন্ট ও সামনের জিপার পকেট ভ্রমণ বা অফিসের জন্য আদর্শ।",
    storyEn: "Custom engineered in Manikganj with reinforced stress-points to combine heritage craftsmanship with outdoor readiness.",
    storyBn: "মানিকগঞ্জ ওয়ার্কশপে বিশেষ ডাবল রিইনফোর্সমেন্টে তৈরি যাতে দৈনন্দিন ভ্রমণ ও আউটিংয়ে দীর্ঘদিন ব্যবহার করা যায়।",
    featuresEn: [
      "Genuine leather flap closures with dual quick-release magnetic brass snaps",
      "Large front cargo pocket for chargers, passport, and daily gear",
      "Adjustable padded shoulder straps for all-day carrying comfort",
      "Fits 14-inch laptops and weekend travel apparel",
    ],
    featuresBn: [
      "জেনুইন লেদার ফ্ল্যাপ ও দ্রুত খোলার ম্যাগনেটিক ব্রাস স্ন্যাপ",
      "সামনে পাসপোর্ট, চার্জার ও প্রয়োজনীয় সামগ্রী রাখার বড় পকেট",
      "সারাদিন আরামদায়কভাবে পিঠে বহনের জন্য প্যাডেড স্ট্র্যাপ",
      "১৪ ইঞ্চি ল্যাপটপ ও উইকএন্ড ভ্রমণের কাপড়চোপড় ধারণে সক্ষম",
    ],
    dimensionsEn: "13\" W x 16\" H x 6\" D",
    dimensionsBn: "১৩\" চওড়া × ১৬\" উচ্চতা × ৬\" গভীরতা",
    materialEn: "Heavy-Woven Jute Canvas & Genuine Distressed Leather",
    materialBn: "ঘন বুননের জুট ক্যানভাস ও জেনুইন ডিসট্রেসড লেদার",
    careEn: ["Spot clean fabric with gentle soap water", "Keep leather dry and conditioned"],
    careBn: ["হালকা সাবান পানি দিয়ে কাপড়ের দাগ মুছুন", "লেদার অংশ শুকনো রাখুন"],
    primaryImage: "/images/products/travel-backpack.jpg",
    images: ["/images/products/travel-backpack.jpg", "/images/products/laptop-bag.jpg"],
    badge: { text: "নতুন কালেকশন", textEn: "New Luxury", variant: "neutral" },
    isFeatured: true,
    inStock: true,
    rating: 5.0,
    reviewsCount: 39,
    variants: [
      { k: "std", en: "Classic Canvas", bn: "ক্লাসিক ক্যানভাস", price: 1850 },
    ],
  },
  {
    id: "P06",
    cat: "home",
    slug: "jute-storage-basket",
    en: "Braided Spiral Jute Storage Basket",
    bn: "পাটের স্টোরেজ ঝুড়ি",
    taglineEn: "Coiled Scandinavian warmth for clutter-free living rooms and closets",
    taglineBn: "হাতে বোনা স্পাইরাল ব্রেইডেড ঝুড়ি · পরিপাটি ঘরের নান্দনিক সঙ্গী",
    descriptionEn: "Hand-coiled by skilled artisans using thick braided jute rope with a soft natural cotton linen inner lining. Perfect for storing throws, magazines, children's toys, laundry, or potted indoor planters with Scandinavian elegance.",
    descriptionBn: "মোটা ব্রেইডেড পাটের দড়ির স্পাইরাল বুননে হাতে তৈরি স্টোরেজ বাস্কেট। ভেতরের সফট সুতি লিনেন লাইনিং জিনিসপত্রকে সুরক্ষিত রাখে। কাপড়, খেলনা, তোয়ালে বা ইনডোর টব সাজিয়ে রাখার জন্য ড্রয়িংরুম ও বেডরুমে এনে দেয় স্ক্যান্ডিনেভিয়ান লুক।",
    storyEn: "Braided continuously in a concentric spiral by master rope weavers in Manikganj.",
    storyBn: "মানিকগঞ্জের অভিজ্ঞ তাঁতিদের নিপুণ হাতে একটানা গোল স্পাইরাল বুননে প্রস্তুত।",
    featuresEn: [
      "Stands upright independently with thick coiled rope structure",
      "Removable & washable natural cotton-linen fabric inner liner",
      "Dual integrated sturdy carrying handles on sides",
      "Versatile utility across bedrooms, living rooms, and nursery",
    ],
    featuresBn: [
      "মোটা দড়ির বুনন তাই কোনো সাপোর্ট ছাড়াই সোজা দাঁড়িয়ে থাকে",
      "ভেতরে সহজে খুলে ধোয়ার উপযোগী কটন-লিনেন কাপড় লাইনিং",
      "সহজে এক স্থান থেকে অন্য স্থানে নেওয়ার জন্য দুই পাশে মজবুত হাতল",
      "বেডরুম, লিভিং রুম বা খেলনা গুছিয়ে রাখার বহুমুখী ব্যবহার",
    ],
    dimensionsEn: "Small: 8x8\", Medium: 10x10\", Large: 12x12\"",
    dimensionsBn: "ছোট: ৮×৮\", মাঝারি: ১০×১০\", বড়: ১২×১২\" ইঞ্চি",
    materialEn: "100% Concentric Braided Jute with Linen Liner",
    materialBn: "১০০% স্পাইরাল ব্রেইডেড সোনালি পাট ও সুতি লিনেন লাইনার",
    careEn: ["Wipe clean with a damp cloth", "Removable liner can be gently hand-washed"],
    careBn: ["ভেজা কাপড় দিয়ে বাইরের পাট মুছে নিন", "ভেতরের লাইনার খুলে হাত দিয়ে ধোয়া যাবে"],
    primaryImage: "/images/products/storage-basket.jpg",
    images: ["/images/products/storage-basket.jpg", "/images/products/laundry-hamper.jpg"],
    badge: { text: "১৫% ছাড়", textEn: "15% Off", variant: "sale" },
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 115,
    variants: [
      { k: "S", en: "Small (8x8\")", bn: "ছোট (৮×৮ ইঞ্চি)", price: 450 },
      { k: "M", en: "Medium (10x10\")", bn: "মাঝারি (১০×১০ ইঞ্চি)", price: 650 },
      { k: "L", en: "Large (12x12\")", bn: "বড় (১২×১২ ইঞ্চি)", price: 850 },
    ],
  },
  {
    id: "P07",
    cat: "home",
    slug: "laundry-hamper",
    en: "Tall Cylindrical Jute Laundry Hamper Basket with Lid",
    bn: "ঢাকনাযুক্ত পাটের লন্ড্রি বাস্কেট",
    taglineEn: "Freestanding Japandi hamper basket with fitted lid and rope handles",
    taglineBn: "জাপান্দি ডিজাইনের লম্বা সিলিন্ডার লন্ড্রি ঝুড়ি ও ঢাকনা",
    descriptionEn: "Elevate your bathroom, laundry room, or master suite with this tall cylindrical hamper. Features an all-natural coiled jute construction, fitted matching lid to keep laundry discreet, and dual thick nautical cotton rope handles.",
    descriptionBn: "বাথরুম বা বেডরুমের আভিজাত্য বাড়াতে তৈরি লম্বা সিলিন্ডার আকৃতির লন্ড্রি বাস্কেট। ঘন ব্রেইডেড খাঁটি পাটের বুনন, ময়লা কাপড় ঢেকে রাখার জন্য ম্যাচিং ঢাকনা এবং সহজে বহনের জন্য শক্ত নটিক্যাল কটন রোপ হ্যান্ডেল।",
    storyEn: "Woven meticulously in Manikganj Sadar, embodying zero-waste Japandi aesthetic.",
    storyBn: "মানিকগঞ্জ সদরে পরিবেশবান্ধব উপায়ে হাতে বোনা আধুনিক মিনিমালিস্ট লন্ড্রি সল্যুশন।",
    featuresEn: [
      "Fitted matching jute lid keeps laundry concealed and dust-free",
      "Thick white cotton rope handles secured with heavy-duty anchors",
      "Sturdy 22-inch height accommodates 3-4 days of family laundry",
      "Breathable natural jute fibers naturally prevent odors and dampness",
    ],
    featuresBn: [
      "ম্যাচিং ঢাকনা যা ভেতরের কাপড় ঢেকে রাখে ও ধুলোবালি প্রতিরোধ করে",
      "দুই পাশে মজবুত সাদা সুতি রোপ হ্যান্ডেল",
      "২২ ইঞ্চি লম্বা ধারণক্ষমতা যা পুরো পরিবারের ৩-৪ দিনের কাপড় ধারণ করে",
      "প্রাকৃতিক পাটের ভেন্টিলেশন কাপড়ে কোনো ভ্যাপসা গন্ধ সৃষ্টি হতে দেয় না",
    ],
    dimensionsEn: "15\" Diameter x 22\" Height",
    dimensionsBn: "১৫\" ব্যাস × ২২\" উচ্চতা",
    materialEn: "Coiled Natural Jute & Twisted Cotton Rope",
    materialBn: "স্পাইরাল ব্রেইডেড খাঁটি পাট ও টুইস্টেড কটন রোপ",
    careEn: ["Spot wipe with dry or slightly damp cloth", "Keep in well-ventilated dry spaces"],
    careBn: ["শুকনো বা হালকা ভেজা কাপড় দিয়ে মুছুন", "বাতাস চলাচল করে এমন শুকনো জায়গায় রাখুন"],
    primaryImage: "/images/products/laundry-hamper.jpg",
    images: ["/images/products/laundry-hamper.jpg", "/images/products/storage-basket.jpg"],
    badge: { text: "প্রিমিয়াম", textEn: "Premium Living", variant: "neutral" },
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 52,
    variants: [
      { k: "std", en: "Tall Cylinder (15x22\")", bn: "লম্বা সিলিন্ডার (১৫×২২ ইঞ্চি)", price: 1650 },
    ],
  },
  {
    id: "P08",
    cat: "home",
    slug: "jute-floor-rug",
    en: "Mandala Spiral Braided Jute Floor Rug",
    bn: "পাটের ফ্লোর ম্যাট / কার্পেট",
    taglineEn: "Concentric circular mandala braiding bringing organic warmth to floors",
    taglineBn: "বৃত্তাকার মান্দালা নকশার হ্যান্ড-ব্রেইডেড পাটের ফ্লোর রাগ",
    descriptionEn: "Make an architectural statement in your living room, entryway, or bedside. Hand-plaited from 100% high-tensile golden jute braids coiled into a balanced concentric mandala pattern. Naturally anti-static, insulating, and wonderfully durable under high foot-traffic.",
    descriptionBn: "লিভিং রুম, বেডরুম বা ডাইনিং স্পেসে প্রাকৃতিক উষ্ণতা ও আভিজাত্য এনে দেওয়ার জন্য বৃত্তাকার মান্দালা ডিজাইনের পাটের ফ্লোর রাগ। উচ্চমানের সোনালি আঁশ দিয়ে হাতে বোনা। এটি অ্যান্টি-স্ট্যাটিক, তাপ প্রতিরোধক এবং দীর্ঘ বছর চলাচলেও অক্ষত থাকে।",
    storyEn: "Hand-plaited on traditional wooden floor frames by rural master weavers in Manikganj.",
    storyBn: "মানিকগঞ্জের ঐতিহ্যবাহী তাঁত শিল্পীদের দ্বারা কাঠের ফ্রেমে পরম যত্নে বোনা।",
    featuresEn: [
      "Reversible double-sided wear for extended lifespan",
      "Naturally acoustic-absorbing and thermally insulating underfoot",
      "Stitched with heavy invisible filament to prevent unraveling",
      "Lays flat and smooth on hardwood, tiles, or marble flooring",
    ],
    featuresBn: [
      "উভয় পিঠ সমানভাবে ব্যবহারযোগ্য যা দীর্ঘস্থায়িত্ব নিশ্চিত করে",
      "মেঝের আওয়াজ শোষণ করে ও শীতকালে মেঝের উষ্ণতা বজায় রাখে",
      "নিখুঁত লক-স্টিচ সেলাই যাতে কোনো সুতো আলগা না হয়",
      "মার্বেল বা টাইলস মেঝের ওপর সম্পূর্ণ সমানভাবে বসে থাকে",
    ],
    dimensionsEn: "2x3 ft (Entryway/Bedside) & 3x5 ft (Living/Lounge)",
    dimensionsBn: "২×৩ ফুট (প্রবেশদ্বার/সাইড) এবং ৩×৫ ফুট (লিভিং রুম)",
    materialEn: "100% Unbleached High-Tensile Golden Jute",
    materialBn: "১০০% প্রাকৃতিক হাই-টেনসিল সোনালি আঁশ",
    careEn: ["Vacuum regularly without beater bar", "Shake out dust outdoors", "Spot clean immediately"],
    careBn: ["নিয়মিত ভ্যাকুয়াম বা ঝাড়ু দিন", "বাইরে নিয়ে ঝেড়ে ফেলুন", "দাগ লাগলে সাথে সাথে ভেজা কাপড় দিয়ে মুছুন"],
    primaryImage: "/images/products/floor-rug.jpg",
    images: ["/images/products/floor-rug.jpg", "/images/products/cushion-cover.jpg"],
    badge: { text: "১০০% প্রাকৃতিক", textEn: "100% Organic", variant: "eco" },
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    rating: 4.8,
    reviewsCount: 88,
    variants: [
      { k: "2x3", en: "2x3 Feet (Bedside)", bn: "২×৩ ফুট (বেডসাইড)", price: 1200 },
      { k: "3x5", en: "3x5 Feet (Living Lounge)", bn: "৩×৫ ফুট (লিভিং লাউঞ্জ)", price: 2400 },
    ],
  },
  {
    id: "P09",
    cat: "home",
    slug: "jute-cushion-cover",
    en: "Luxury Textured Jute Cushion Cover with Fringed Border",
    bn: "পাটের কুশন কভার ১৬×১৬",
    taglineEn: "Scandinavian bohemian sofa accent with delicate frayed tassel fringe",
    taglineBn: "ফ্রিঞ্জ ট্যাসেল বর্ডারসহ স্ক্যান্ডিনেভিয়ান লিভিং রুম কুশন কভার",
    descriptionEn: "Infuse modern organic texture into your sofa, daybed, or reading nook. Woven from breathable raw jute fibers with an artisanal frayed fringe border and a concealed back zipper for easy pillow insertion.",
    descriptionBn: "আপনার ড্রয়িংরুমের সোফা বা বেডরুমে স্ক্যান্ডিনেভিয়ান বোহো লুক এনে দিতে সূক্ষ্ম বুননের পাটের কুশন কভার। চারপাশের নান্দনিক ফ্রিঞ্জ ট্যাসেল বর্ডার এবং পেছনের লুকানো জিপার এটিকে অত্যন্ত রুচিশীল ও ব্যবহারবান্ধব করে তুলেছে।",
    storyEn: "Woven on compact wooden handlooms in Manikganj with soft combed jute yarns.",
    storyBn: "মানিকগঞ্জের হ্যান্ডলুম তাঁতে বিশেষ প্রক্রিয়াজাত কোমল পাটের সুতো দিয়ে বোনা।",
    featuresEn: [
      "Artisanal frayed raw fringe border around all four edges",
      "Hidden color-matched back zipper for seamless aesthetics",
      "Pre-softened combed jute fabric comfortable for lounging",
      "Standard 16x16 inch size fitting all standard throw pillow inserts",
    ],
    featuresBn: [
      "চারপাশে নান্দনিক ফ্রিঞ্জ ট্যাসেল বর্ডার ফিনিশিং",
      "পেছনে লুকানো ম্যাচিং জিপার যা সহজে কুশন ঢোকাতে সাহায্য করে",
      "বিশেষভাবে সফট করা পাটের ফ্যাব্রিক যা সোফায় হেলান দিতে আরামদায়ক",
      "স্ট্যান্ডার্ড ১৬×১৬ ইঞ্চি সাইজ যা যেকোনো সাধারণ কুশনে মানিয়ে যায়",
    ],
    dimensionsEn: "16\" x 16\" (Fits 16\" or 18\" Inserts)",
    dimensionsBn: "১৬×১৬ ইঞ্চি (১৬ বা ১৮ ইঞ্চি কুশন ইনসার্টের উপযোগী)",
    materialEn: "Combed Natural Jute Face with Soft Cotton Backing",
    materialBn: "কোমল পাটের সম্মুখভাগ ও সফট কটন পেছনের স্তর",
    careEn: ["Dry clean or spot clean only", "Iron on reverse with low steam"],
    careBn: ["ড্রাই ক্লিন বা হালকা ভেজা কাপড় দিয়ে মুছুন", "উল্টো পিঠে হালকা ইস্ত্রি করুন"],
    primaryImage: "/images/products/cushion-cover.jpg",
    images: ["/images/products/cushion-cover.jpg", "/images/products/floor-rug.jpg"],
    inStock: true,
    rating: 4.7,
    reviewsCount: 64,
    variants: [
      { k: "std", en: "Square 16x16\"", bn: "বর্গাকার ১৬×১৬ ইঞ্চি", price: 350 },
    ],
  },
  {
    id: "P10",
    cat: "home",
    slug: "macrame-tapestry",
    en: "Boho Macrame Jute Wall Hanging Tapestry on Driftwood",
    bn: "পাটের মেক্রামে ওয়াল হ্যাঙ্গিং ট্যাপেস্ট্রি",
    taglineEn: "Intricate geometric knotting suspended from natural driftwood",
    taglineBn: "প্রাকৃতিক ড্রিফটউডে ঝুলানো নিখুঁত বোহো মেক্রামে ওয়াল আর্ট",
    descriptionEn: "Turn blank walls into an architectural gallery. This large bohemian wall hanging is knotted by hand using unbleached golden jute twine suspended from a smooth, naturally aged driftwood branch. The rich chevron and diamond macrame textures radiate artisanal soul.",
    descriptionBn: "দেয়ালের সৌন্দর্য দ্বিগুণ করতে তৈরি পাটের মেক্রামে ওয়াল আর্ট। মসৃণ প্রাকৃতিক কাঠের ডালে ঝুলানো খাঁটি পাটের সুতোর নিখুঁত জ্যামিতিক নট ও ফ্রিঞ্জ বুনন। ড্রয়িংরুম, ডায়নিং বা করিডোরের দেয়ালে এটি প্রাকৃতিক উষ্ণতা ও শৈল্পিক আভিজাত্য এনে দেয়।",
    storyEn: "Tied knot by knot by master women artisans in Manikganj, each piece taking over 12 hours of focused hand-knotting.",
    storyBn: "মানিকগঞ্জের নারী কারিগরদের ১২ ঘণ্টার একাগ্র নট বুননে প্রতিটি ট্যাপেস্ট্রি অনন্য শিল্পকর্মে রূপ নেয়।",
    featuresEn: [
      "Authentic solid natural driftwood suspension branch included",
      "Intricate multi-tier chevron, diamond and tassel macrame patterning",
      "Ready to hang with included heavy-duty jute hanging rope",
      "Transforms living rooms, bedroom headboards, and cafe walls",
    ],
    featuresBn: [
      "প্রাকৃতিক কাঠের ডালসহ সম্পূর্ণ প্রস্তুত হ্যাঙ্গিং সেট",
      "শেভরন, ডায়মন্ড ও ট্যাসেল সমন্বিত মাল্টি-লেয়ার বুনন",
      "ঝুলানোর জন্য শক্ত পাটের দড়িসহ দেয়ালে সহজেই স্থাপনযোগ্য",
      "লিভিং রুম, বেডরুম বা অফিসের দেয়ালকে আকর্ষণীয় রূপ দেয়",
    ],
    dimensionsEn: "24\" Branch Width x 32\" Hanging Length",
    dimensionsBn: "২৪\" কাঠের চওড়া × ৩২\" ঝুলন্ত দৈর্ঘ্য",
    materialEn: "100% Hand-Twisted Golden Jute Twine & Natural Branch",
    materialBn: "১০০% টুইস্টেড সোনালি পাট ও প্রাকৃতিক কাঠ",
    careEn: ["Gently comb fringe tassels with a wide-tooth comb", "Lightly dust with feather duster"],
    careBn: ["ফ্রিঞ্জ ট্যাসেলগুলো চিরুনি দিয়ে আলতো করে আঁচড়ে নিন", "হালকা ডাস্টার দিয়ে ধুলোবালি ঝাড়ুন"],
    primaryImage: "/images/products/macrame-tapestry.jpg",
    images: ["/images/products/macrame-tapestry.jpg", "/images/products/plant-hanger.jpg"],
    badge: { text: "হস্তশিল্প", textEn: "Artisan Craft", variant: "handmade" },
    isFeatured: true,
    inStock: true,
    rating: 5.0,
    reviewsCount: 45,
    variants: [
      { k: "std", en: "Large (24x32\")", bn: "বড় সাইজ (২৪×৩২ ইঞ্চি)", price: 1450 },
    ],
  },
  {
    id: "P11",
    cat: "home",
    slug: "jute-plant-hanger",
    en: "Traditional Macrame Jute Plant Hanger (Shika)",
    bn: "ঐতিহ্যবাহী পাটের শিকা (প্ল্যান্ট হ্যাঙ্গার)",
    taglineEn: "Authentic Bengal shika knotting bringing hanging greenery indoors",
    taglineBn: "বাংলার গ্রামীণ ঐতিহ্যের মেক্রামে শিকা · ইনডোর টবের সেরা সঙ্গী",
    descriptionEn: "Celebrate timeless rural heritage. This traditional macrame jute plant hanger (Shika) holds plant pots from 5 to 10 inches securely with a braided top hanging loop and flowing tassel bottom. Perfect for pothos, ferns, and succulents in balconies or windows.",
    descriptionBn: "বাংলার হাজার বছরের ঐতিহ্যের প্রতীক শিকা। বারান্দা, জানালা বা ড্রয়িংরুমে মানিপ্ল্যান্ট বা ইনডোর টব ঝুলিয়ে রাখার জন্য নিখুঁত মেক্রামে নট দিয়ে বোনা। ৫ থেকে ১০ ইঞ্চি মাপের যেকোনো টব নিরাপদে ধারণ করে।",
    storyEn: "Hand-knotted using age-old ancestral village knot patterns from Manikganj.",
    storyBn: "মানিকগঞ্জের বংশপরম্পরায় চলে আসা ঐতিহ্যের কারিগরি নকশায় হাতে বোনা।",
    featuresEn: [
      "Accommodates ceramic, terracotta, or plastic planters (5\" to 10\")",
      "Reinforced top braided hanging loop easily attaches to hooks",
      "Sturdy 4-leg cradle distributing planter weight evenly",
      "36-inch length with dramatic flowing bottom fringe",
    ],
    featuresBn: [
      "সিরামিক, মাটি বা প্লাস্টিকের যেকোনো টব (৫ থেকে ১০ ইঞ্চি) সুন্দরভাবে বসে",
      "মজবুত হ্যান্ড-ব্রেইডেড রিং যা হুকের সাথে সহজে ঝোলানো যায়",
      "৪টি শক্ত দড়ির ভারসাম্যপূর্ণ খাঁচা যা টবের ওজন সমানভাবে ধরে রাখে",
      "৩৬ ইঞ্চি লম্বা ঝুল ও নিচে আকর্ষণীয় ট্যাসেল",
    ],
    dimensionsEn: "36\" Total Hanging Length",
    dimensionsBn: "৩৬\" মোট ঝুলন্ত দৈর্ঘ্য",
    materialEn: "Natural 4-Ply Twisted Golden Jute Cord",
    materialBn: "খাঁটি ৪-প্লাই টুইস্টেড সোনালি পাটের দড়ি",
    careEn: ["Keep dry; remove planter when watering if necessary"],
    careBn: ["গাছে অতিরিক্ত পানি দেওয়ার সময় টব নামিয়ে পানি ঝরিয়ে নিন"],
    primaryImage: "/images/products/plant-hanger.jpg",
    images: ["/images/products/plant-hanger.jpg", "/images/products/macrame-tapestry.jpg"],
    badge: { text: "ঐতিহ্যবাহী", textEn: "Heritage", variant: "handmade" },
    inStock: true,
    rating: 4.8,
    reviewsCount: 96,
    variants: [
      { k: "std", en: "Standard 36\"", bn: "স্ট্যান্ডার্ড ৩৬ ইঞ্চি ঝুল", price: 400 },
    ],
  },
  {
    id: "P12",
    cat: "table",
    slug: "jute-table-runner",
    en: "Artisanal Hand-Woven Jute Dining Table Runner",
    bn: "পাটের ডাইনিং টেবিল রানার",
    taglineEn: "Organic warmth for dinner parties, festive tables, and ceramic ware",
    taglineBn: "হাতে বোনা সোনালি পাটের ডাইনিং টেবিল রানার · আভিজাত্যের স্পর্শ",
    descriptionEn: "Transform everyday meals into an artisanal dining experience. Hand-woven on pit looms using combed golden jute yarns with neatly finished fringe tassels at both ends. Naturally heat-resistant, protecting your wooden or glass table against hot dishes.",
    descriptionBn: "ডাইনিং টেবিলকে আরও আকর্ষণীয় ও রুচিশীল করে তোলার জন্য খাঁটি পাটের ডাইনিং রানার। দুই প্রান্তের নিখুঁত ফ্রিঞ্জ ট্যাসেল এবং মাটির বা সিরামিক পাত্রের সাথে এটি অনন্য মানিয়ে যায়। প্রাকৃতিক তাপ-প্রতিরোধক গুণ টেবিলকে গরম পাত্র থেকে সুরক্ষিত রাখে।",
    storyEn: "Woven on wooden pit-looms in Manikganj, dried under gentle autumn sunshine.",
    storyBn: "মানিকগঞ্জের ঐতিহ্যবাহী তাঁতে রোদে শুকানো সোনালি আঁশ দিয়ে পরম যত্নে বোনা।",
    featuresEn: [
      "Natural thermal resistance shielding table surfaces from warm cookware",
      "Hand-knotted tassel fringe along both narrow ends",
      "14x72 inch length perfectly draping 6 to 8-seater dining tables",
      "Complements both modern minimalism and rustic farmhouses",
    ],
    featuresBn: [
      "টেবিলকে গরম খাবারের পাত্র ও স্ক্র্যাচ থেকে সুরক্ষিত রাখে",
      "দুই প্রান্তে সুদৃশ্য হাতে বাঁধা ট্যাসেল ফ্রিঞ্জ ফিনিশিং",
      "১৪×৭২ ইঞ্চি মাপ যা ৬ থেকে ৮ সিটের ডাইনিং টেবিলে সুন্দরভাবে ড্র্যাপ করে",
      "আধুনিক ও ট্র্যাডিশনাল যেকোনো ঘর সাজানোর সাথে মানানসই",
    ],
    dimensionsEn: "14\" Width x 72\" Length (Includes Tassels)",
    dimensionsBn: "১৪\" চওড়া × ৭২\" দৈর্ঘ্য (ট্যাসেল সহ)",
    materialEn: "100% Handloom Combed Golden Jute",
    materialBn: "১০০% হ্যান্ডলুম সোনালি পাট",
    careEn: ["Spot wipe with a moist cloth", "Do not wring or tumble dry", "Iron over a cloth with steam"],
    careBn: ["ভেজা কাপড় দিয়ে মুছুন", "চিপবেন না বা মেশিনে শুকাবেন না", "হালকা সুতি কাপড়ের ওপর দিয়ে আয়রন করুন"],
    primaryImage: "/images/products/table-runner.jpg",
    images: ["/images/products/table-runner.jpg", "/images/products/placemat-set.jpg"],
    badge: { text: "বেস্টসেলার", textEn: "Popular", variant: "handmade" },
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 104,
    variants: [
      { k: "std", en: "Standard (14x72\")", bn: "স্ট্যান্ডার্ড (১৪×৭২ ইঞ্চি)", price: 550 },
    ],
  },
  {
    id: "P13",
    cat: "table",
    slug: "jute-placemat-set",
    en: "Circular Braided Jute Placemats & Coasters (Set of 6)",
    bn: "পাটের প্লেসম্যাট সেট (৬টি)",
    taglineEn: "Heat-resistant braided charger mats protecting table finishes",
    taglineBn: "বৃত্তাকার ব্রেইডেড ৬ পিস ডাইনিং প্লেসম্যাট ও কোস্টার সেট",
    descriptionEn: "Complete your tablescape with this artisanal 6-piece dining placemat set. Crafted from concentric tightly-coiled jute braids, each placemat acts as a natural heat barrier, crumb catcher, and eye-catching dining charger.",
    descriptionBn: "ডাইনিং টেবিল সাজানোর পূর্ণাঙ্গ ৬ পিস প্লেসম্যাট সেট। ঘন ব্রেইডেড সোনালি পাটের বৃত্তাকার বুনন। প্লেটের তাপ প্রতিরোধ করতে এবং টেবিলকে স্ক্র্যাচ ও দাগ থেকে বাঁচাতে অত্যন্ত কার্যকর ও রুচিশীল।",
    storyEn: "Stitched concentrically by skilled women artisans in Manikganj using heavy-gauge natural thread.",
    storyBn: "মানিকগঞ্জের নারী কারিগরদের নিপুণ হাতে শক্ত সুতো দিয়ে গোল করে সেলাই করা।",
    featuresEn: [
      "Set includes 6 identical 14-inch circular dining placemats",
      "Heat-insulating barrier protecting glass and wood tables",
      "Flat non-slip profile sitting securely under heavy dinnerware",
      "Easy maintenance: simply shake off crumbs and wipe clean",
    ],
    featuresBn: [
      "সেটে রয়েছে ৬টি ১৪ ইঞ্চি সাইজের গোল ডাইনিং প্লেসম্যাট",
      "কাঁচ বা কাঠের টেবিলকে গরম বাটির দাগ থেকে রক্ষা করে",
      "টেবিলের ওপর দৃঢ়ভাবে বসে থাকে, পিছলে যায় না",
      "সহজে পরিষ্কারযোগ্য: ঝেড়ে নিয়ে ভেজা কাপড় দিয়ে মুছলেই নতুনের মতো",
    ],
    dimensionsEn: "14\" Diameter Each (Set of 6)",
    dimensionsBn: "প্রতিটি ১৪\" ব্যাস (৬টির সেট)",
    materialEn: "100% Braided Natural Jute Fibre",
    materialBn: "১০০% ব্রেইডেড প্রাকৃতিক সোনালি পাট",
    careEn: ["Wipe clean with a damp sponge", "Do not submerge in water"],
    careBn: ["ভেজা স্পঞ্জ দিয়ে মুছে পরিষ্কার করুন", "পানিতে সম্পূর্ণ ডুবাবেন না"],
    primaryImage: "/images/products/placemat-set.jpg",
    images: ["/images/products/placemat-set.jpg", "/images/products/table-runner.jpg"],
    inStock: true,
    rating: 4.8,
    reviewsCount: 78,
    variants: [
      { k: "std", en: "Set of 6 (14\" Mats)", bn: "৬টির সেট (১৪ ইঞ্চি)", price: 900 },
    ],
  },
  {
    id: "P14",
    cat: "table",
    slug: "bottle-carrier",
    en: "Luxury Dual-Bottle Jute Carrier with Bamboo Handle",
    bn: "পাটের বোতল ও বেভারেজ ক্যারিয়ার ব্যাগ",
    taglineEn: "Artisanal twin bottle carrier with reinforced divider and cane arch",
    taglineBn: "বাঁশের হাতলযুক্ত ২টি বোতল বহনের প্রিমিয়াম পাটের ব্যাগ",
    descriptionEn: "Designed for picnics, dinner invitations, and gift presentations. This handcrafted tote carries two bottles of beverage, cold-pressed oil, or artisanal syrups safely separated by a padded center divider, complete with an arched solid bamboo handle.",
    descriptionBn: "পিকনিক, দাওয়াত বা গিফট দেওয়ার জন্য তৈরি ২টি বোতল বহনের এক্সক্লুসিভ পাটের ক্যারিয়ার। ভেতরের প্যাডেড পার্টিশন দুটি বোতলকে ধাক্কা খাওয়া থেকে নিরাপদ রাখে। মজবুত বাঁশের আর্চ হ্যান্ডেল হাতে বহনে এনে দেয় আভিজাত্য।",
    storyEn: "Structured and assembled by hand in Manikganj with reinforced antique brass rivets.",
    storyBn: "মানিকগঞ্জে অ্যান্টিক ব্রাস রিভেট ও টেকসই বাঁশ দিয়ে হাতে তৈরি।",
    featuresEn: [
      "Center padded divider preventing glass bottles from clinking",
      "Arched solid polished bamboo handle for comfortable balanced carrying",
      "Reinforced firm base preventing sagging under heavy glass weight",
      "Ideal gift packaging for weddings, corporate tokens, and hosts",
    ],
    featuresBn: [
      "ভেতরের পার্টিশন বোতল দুটিকে পরস্পর ধাক্কা খাওয়া থেকে রক্ষা করে",
      "হাতে সহজে বহনের জন্য শক্ত ও সুন্দর বাঁশের আর্চ হ্যান্ডেল",
      "শক্ত তলা যা বোতলের ভারে বাঁকা হয় না",
      "বিয়ে, উৎসব বা কর্পোরেট উপহার দেওয়ার প্রিমিয়াম প্যাকেজিং",
    ],
    dimensionsEn: "9\" W x 14\" H x 4.5\" D",
    dimensionsBn: "৯\" চওড়া × ১৪\" উচ্চতা × ৪.৫\" গভীরতা",
    materialEn: "Textured Heavy Jute Weave & Solid Polished Bamboo",
    materialBn: "টেক্সচার্ড হেভি জুট ও পালিশ করা বাঁশ",
    careEn: ["Wipe clean with a damp cloth", "Store in a dry location"],
    careBn: ["হালকা ভেজা কাপড় দিয়ে মুছুন", "শুকনো জায়গায় সংরক্ষণ করুন"],
    primaryImage: "/images/products/bottle-carrier.jpg",
    images: ["/images/products/bottle-carrier.jpg", "/images/products/gift-box.jpg"],
    badge: { text: "উপহার স্পেশাল", textEn: "Gift Special", variant: "handmade" },
    inStock: true,
    rating: 4.9,
    reviewsCount: 36,
    variants: [
      { k: "std", en: "Dual Bottle Carrier", bn: "২টি বোতল ক্যারিয়ার", price: 580 },
    ],
  },
  {
    id: "P15",
    cat: "office",
    slug: "jute-file-folder",
    en: "Executive Conference Jute Document Portfolio & Folder",
    bn: "এক্সিকিউটিভ পাটের ফাইল ফোল্ডার",
    taglineEn: "Impress clients at summits, meetings, and boardrooms with eco-luxury",
    taglineBn: "লেদার বাটন ক্লিপযুক্ত কর্পোরেট কনফারেন্স ডকু ফোল্ডার",
    descriptionEn: "Replace synthetic vinyl portfolios with this distinguished executive folder. Handcrafted from fine-textured laminated jute canvas with saddle leather button strap closure. Accommodates standard A4 and legal paper documents, legal pad, and business cards.",
    descriptionBn: "কর্পোরেট মিটিং, কনফারেন্স ও সেমিনারে প্লাস্টিক ফোল্ডারের বিকল্প হিসেবে অনন্য পাটের এক্সিকিউটিভ ফোল্ডার। সূক্ষ্ম বুননের পাট ও খাঁটি লেদার বাটন স্ট্র্যাপ দিয়ে তৈরি। এ৪ সাইজের ডকুমেন্ট, নোটপ্যাড ও ভিজিটিং কার্ড রাখার জন্য উপযুক্ত।",
    storyEn: "Widely selected by banks, universities, and multinationals in Dhaka and international forums.",
    storyBn: "বিভিন্ন ব্যাংক, এনজিও ও বহুজাতিক প্রতিষ্ঠানের কনফারেন্সে বিশেষ সমাদৃত।",
    featuresEn: [
      "Fits A4 and Letter documents comfortably without bending",
      "Genuine leather tab with brass snap button closure",
      "Inner slip pocket for business cards and loose notes",
      "Customizable with screen-printed or stamped company logo for bulk orders",
    ],
    featuresBn: [
      "এ৪ সাইজের কাগজপত্র ও নোটবুক কোনো ভাঁজ ছাড়াই সহজে ধরে",
      "জেনুইন লেদার ট্যাব ও মেটালিক ব্রাস স্ন্যাপ বাটন",
      "ভেতরে ভিজিটিং কার্ড ও প্রয়োজনীয় কাগজ রাখার পকেট",
      "বাল্ক অর্ডারে প্রতিষ্ঠানের লোগো প্রিন্ট বা এমবস করার সুবিধা",
    ],
    dimensionsEn: "13.5\" W x 10\" H (Closed A4 Profile)",
    dimensionsBn: "১৩.৫\" চওড়া × ১০\" উচ্চতা (এ৪ সাইজ)",
    materialEn: "Fine-Loom Jute Fabric, Saddle Leather, Brass Button",
    materialBn: "ফাইন-লুম পাটের কাপড়, স্যাডেল লেদার, ব্রাস বাটন",
    careEn: ["Wipe clean with a dry or slightly damp cloth"],
    careBn: ["শুকনো বা সামান্য ভেজা কাপড় দিয়ে মুছুন"],
    primaryImage: "/images/products/file-folder.jpg",
    images: ["/images/products/file-folder.jpg", "/images/products/laptop-bag.jpg"],
    badge: { text: "কর্পোরেট সেরা", textEn: "B2B Favorite", variant: "neutral" },
    inStock: true,
    rating: 4.9,
    reviewsCount: 112,
    variants: [
      { k: "std", en: "A4 Executive Size", bn: "এ৪ এক্সিকিউটিভ সাইজ", price: 320 },
    ],
  },
  {
    id: "P16",
    cat: "gifts",
    slug: "jute-gift-hamper-box",
    en: "Luxury Woven Jute Gift Box with Ribbon Lid",
    bn: "পাটের গিফট হ্যাম্পার বক্স",
    taglineEn: "Sustainable luxury presentation box for Eid, weddings, and VIP gifts",
    taglineBn: "ঢাকনাসহ বিলাসবহুল পাটের গিফট বক্স · চিরস্থায়ী স্মারক উপহার",
    descriptionEn: "Ditch disposable wrapping paper for an heirloom luxury gift box. Meticulously hand-crocheted from supple golden jute yarns, complete with a structured lid and tied with an ivory grosgrain ribbon bow. Designed to be reused for years as a jewelry or vanity box.",
    descriptionBn: "উৎসব, বিয়ে, ঈদ বা বিশেষ কর্পোরেট গিফটিংয়ের জন্য ঢাকনাসহ বিলাসবহুল পাটের গিফট বক্স। সূক্ষ্ম পাটের সুতোয় হাতে বোনা এবং আইভরি রিবন দিয়ে বাঁধা। উপহার দেওয়ার পর এটি ড্রেসিং টেবিল বা জুয়েলারি বক্স হিসেবে বহু বছর ব্যবহারযোগ্য।",
    storyEn: "Hand-crocheted and bound in Manikganj, turning eco-materials into celebratory tokens.",
    storyBn: "মানিকগঞ্জে গ্রামীণ কারিগরদের নিপুণ ক্রোশে বুননে তৈরি পরিবেশবান্ধব উৎসব উপহার।",
    featuresEn: [
      "Stiff structured lid with ivory ribbon tie closure",
      "Reversible and durable — a gift box that is a present in itself",
      "Generous capacity holding dry fruits, perfume, crafts, or textiles",
      "100% natural, biodegradable, and circular packaging",
    ],
    featuresBn: [
      "মজবুত স্ট্রাকচার্ড ঢাকনা ও সুদৃশ্য আইভরি রিবন বো",
      "উপহারের বাক্সটি নিজেই একটি মূল্যবান দীর্ঘস্থায়ী উপহার",
      "ড্রাই ফ্রুটস, পারফিউম, হস্তশিল্প বা শাড়ি প্যাক করার মতো সুপরিসর",
      "১০০% প্রাকৃতিক, পচনশীল ও পরিবেশবান্ধব",
    ],
    dimensionsEn: "9\" L x 7\" W x 4.5\" H",
    dimensionsBn: "৯\" দৈর্ঘ্য × ৭\" চওড়া × ৪.৫\" উচ্চতা",
    materialEn: "Crocheted Golden Jute with Satin Grosgrain Ribbon",
    materialBn: "হাতে বোনা সোনালি পাট ও গ্রোসগ্রেইন আইভরি রিবন",
    careEn: ["Keep dry; dust lightly with a soft brush"],
    careBn: ["শুকনো জায়গায় রাখুন; নরম ব্রাশ দিয়ে ধুলোবালি ঝাড়ুন"],
    primaryImage: "/images/products/gift-box.jpg",
    images: ["/images/products/gift-box.jpg", "/images/products/bottle-carrier.jpg"],
    badge: { text: "গিফট প্যাক", textEn: "Gift Pack", variant: "neutral" },
    isFeatured: true,
    inStock: true,
    rating: 5.0,
    reviewsCount: 68,
    variants: [
      { k: "std", en: "Medium Luxury Box", bn: "মাঝারি লাক্সারি বক্স", price: 650 },
    ],
  },
  {
    id: "P17",
    cat: "footwear",
    slug: "jute-slippers",
    en: "Eco-Friendly Natural Jute Loafers & House Slippers",
    bn: "পাটের ইকো স্লিপার ও হাউস লোফার",
    taglineEn: "Breathable natural jute fabric with cushioned comfort for indoor lounging",
    taglineBn: "আরামদায়ক কুশন্ড সোলযুক্ত ১০০% পরিবেশবান্ধব পাটের জুতো",
    descriptionEn: "Experience the tactile calm of nature with every step. Crafted with a breathable pure jute woven upper, soft linen edge piping, and a cushioned flexible natural crepe rubber sole. Keeps feet naturally cool in summer and cozy in winter.",
    descriptionBn: "প্রতি পদক্ষেপে প্রকৃতির ছোঁয়া অনুভব করুন। শ্বাসপ্রশ্বাসযোগ্য খাঁটি পাটের বুননের ওপরের অংশ, সফট লিনেন পাইপিং এবং নিচে আরামদায়ক কুশন্ড ন্যাচারাল রাবার সোল। গরমে পা রাখে ঠান্ডা এবং শীতে রাখে আরামদায়ক। ঘরের ভেতরে ও বারান্দায় ব্যবহারের জন্য চমৎকার।",
    storyEn: "Crafted in small batches with zero microplastics, promoting circular footwear in Bangladesh.",
    storyBn: "মানিকগঞ্জের কারিগরদের দ্বারা সীমিত সংস্করণে তৈরি শতভাগ প্লাস্টিকমুক্ত আরামদায়ক জুতো।",
    featuresEn: [
      "Naturally anti-microbial and sweat-wicking jute fiber insole",
      "Flexible, lightweight anti-slip natural crepe rubber outsole",
      "Padded footbed providing all-day indoor arch comfort",
      "Available in unisex sizes 38 to 44",
    ],
    featuresBn: [
      "অ্যান্টি-মাইক্রোবিয়াল ও ঘাম প্রতিরোধক প্রাকৃতিক পাটের ইনসোল",
      "নমনীয়, হালকা ও নন-স্লিপ ন্যাচারাল রাবার আউটসোল",
      "প্যাডেড ফুটবেড যা পায়ে সারাদিন আরাম যোগায়",
      "ইউনিসেক্স সাইজ: ৩৮ থেকে ৪৪ পর্যন্ত",
    ],
    dimensionsEn: "Standard EU Sizes: 38, 39, 40, 41, 42, 43, 44",
    dimensionsBn: "সাইজ: ৩৮, ৩৯, ৪০, ৪১, ৪২, ৪৩, ৪৪",
    materialEn: "Woven Jute Fabric Upper, Linen Trim, Natural Rubber Sole",
    materialBn: "পাটের ফ্যাব্রিক আপার, লিনেন বর্ডার, প্রাকৃতিক রাবার সোল",
    careEn: ["Spot clean with mild damp cloth", "Air dry completely", "Do not machine wash"],
    careBn: ["হালকা ভেজা কাপড় দিয়ে মুছুন", "বাতাসে সম্পূর্ণ শুকিয়ে নিন", "মেশিনে ধোবেন না"],
    primaryImage: "/images/products/jute-slippers.jpg",
    images: ["/images/products/jute-slippers.jpg", "/images/products/floor-rug.jpg"],
    badge: { text: "ইকো ফুটওয়্যার", textEn: "Eco Footwear", variant: "eco" },
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 42,
    variants: [
      { k: "39", en: "Size 39", bn: "সাইজ ৩৯", price: 750 },
      { k: "40", en: "Size 40", bn: "সাইজ ৪০", price: 750 },
      { k: "41", en: "Size 41", bn: "সাইজ ৪১", price: 750 },
      { k: "42", en: "Size 42", bn: "সাইজ ৪২", price: 750 },
    ],
  },
  {
    id: "P18",
    cat: "jewelry",
    slug: "jute-floral-earrings-royal-blue",
    en: "Royal Blue Jute Floral Pearl Earrings",
    bn: "নীলপদ্ম জুট ফ্লাওয়ার পার্ল কানের দুল",
    taglineEn: "Handcrafted 5-petal royal blue coiled jute blossom with luminous pearl center",
    taglineBn: "হাতে বোনা খাঁটি পাটের নীল পাপড়ি ও মুক্তো দানার নান্দনিক যুগলবন্দী",
    descriptionEn: "Exquisitely hand-coiled by rural master artisans, these vibrant royal blue jute earrings feature a five-petal floral motif accented with delicate turquoise and golden yellow threading, crowned by a lustrous pearl bead center. Ultra-lightweight on the earlobe with hypoallergenic gold-tone fish hooks, making them ideal for all-day festive or daily wear.",
    descriptionBn: "গ্রামীণ ঐতিহ্য ও আধুনিক ফ্যাশনের অনন্য সংযোজন—নীলপদ্ম জুট ফ্লাওয়ার ইয়াররিং। ১০০% প্রাকৃতিক সোনালি আঁশকে রয়্যাল ব্লু রঙে রাঙিয়ে সূক্ষ্ম কুন্ডলী (coiled weave) পদ্ধতিতে ৫টি পাপড়ি এবং মাঝে টার্কিশ ব্লু ও হলুদ সুতোর বুননে মুক্তো দানা খচিত। ওজনে অত্যন্ত হালকা ও গোল্ডেন ফিশ-হুক যুক্ত থাকায় সারাদিন পরে থাকলেও কানে কোনো চাপ বা অস্বস্তি হয় না।",
    storyEn: "Crafted individually by skilled women artisans in Manikganj. Each petal is spun and spiraled using fine natural jute twine, taking over two hours of precision micro-weaving.",
    storyBn: "মানিকগঞ্জের নারী কারিগরদের নিপুণ আঙুলের স্পর্শে তৈরি। প্রতিটি কানের দুলের পাপড়ি ও বৃত্ত তৈরি করতে সূক্ষ্ম পাটের আঁশ প্রায় ২ ঘণ্টা ধরে নিখুঁতভাবে প্যাঁচানো ও সাজানো হয়।",
    featuresEn: [
      "100% Biodegradable premium coloured natural jute",
      "Central lustrous faux pearl bead with multi-tone concentric thread rings",
      "Hypoallergenic nickel-free gold-plated ear wire hooks",
      "Ultra-lightweight (~14g per pair) for maximum ear comfort",
      "Perfect match for Jamdani sarees, kurtis, university campuses, and festivals"
    ],
    featuresBn: [
      "১০০% প্রাকৃতিক ও পরিবেশবান্ধব রঙ করা খাঁটি সোনালি পাট",
      "মাঝখানে আকর্ষণীয় মুক্তো দানা ও দ্বিস্তরীয় সুতোর রিং",
      "ত্বকবান্ধব হাইপোঅ্যালার্জেনিক গোল্ড-প্লেটেড ফিশ হুক",
      "কানে অত্যন্ত হালকা (প্রতি জোড়া মাত্র ১৪ গ্রাম) — সারাদিন পরার উপযোগী",
      "জামদানি শাড়ি, ফিউশন পোশাক, পহেলা বৈশাখ বা যেকোনো উৎসবের সাথে নিখুঁত মানানসই"
    ],
    dimensionsEn: "Flower Diameter: 5.5 cm (2.2 in), Drop Length: 6.5 cm, Weight: 14g/pair",
    dimensionsBn: "ফুলের ব্যাস: ৫.৫ সেমি, ঝুলন্ত দৈর্ঘ্য: ৬.৫ সেমি, ওজন: মাত্র ১৪ গ্রাম/জোড়া",
    materialEn: "Natural dyed golden jute, cotton embroidery thread, acrylic pearl bead, brass ear wire",
    materialBn: "প্রাকৃতিক ডাইড সোনালি পাট, কটন সুতো, পার্ল বিড, ব্রাস ফিশ হুক",
    careEn: [
      "Keep away from direct water soaking; gently wipe with a dry soft cloth if dusty",
      "Store in a dry cloth pouch or jewelry box when not in use",
      "Avoid direct heavy perfume spray on the jute fibres"
    ],
    careBn: [
      "সরাসরি পানিতে ভেজানো পরিহার করুন; ধুলো লাগলে শুকনো নরম কাপড় দিয়ে হালকা মুছে নিন",
      "ব্যবহার শেষে শুষ্ক জুয়েলারি বক্সে সংরক্ষণ করুন",
      "পাটের অংশে সরাসরি তীব্র পারফিউম স্প্রে না করার পরামর্শ দেওয়া হচ্ছে"
    ],
    primaryImage: "/images/products/jute-floral-earrings-blue.jpg",
    images: [
      "/images/products/jute-floral-earrings-blue.jpg",
      "/images/products/jute-floral-earrings-blue-model.jpg",
      "/images/products/jute-floral-earrings-blue-stand.jpg"
    ],
    badge: {
      text: "নতুন কালেকশন",
      textEn: "New Arrival",
      variant: "eco"
    },
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 38,
    variants: [
      { k: "single", en: "Single Pair", bn: "১ জোড়া", price: 350 },
      { k: "gift_duo", en: "Duo Gift Box (2 Pairs)", bn: "২ জোড়া গিফট বক্স", price: 650 },
    ],
  },
  {
    id: "P19",
    cat: "jewelry",
    slug: "jute-drop-earrings-crystal-cyan",
    en: "Turquoise Cyan Double Flower Crystal Jute Drop Earrings",
    bn: "আকাশি ঝুমকা ডাবল ফ্লাওয়ার জুট কানের দুল",
    taglineEn: "Two-tier handcrafted turquoise cyan jute flower drops with sparkling faceted crystal centers",
    taglineBn: "দীপ্তিময় ক্রিস্টাল ও টার্কিশ ব্লু পাটের সূক্ষ্ম দুই স্তর ডাবল ড্রপ অলঙ্কার",
    descriptionEn: "A statement artisanal drop earring featuring two cascading five-petal blossoms in refreshing turquoise cyan blue jute. Each flower is centered with a brilliant light-refracting faceted rhinestone set in a warm gold-toned bezel, connected with durable jump rings for graceful movement. Lightweight, dramatic, and exquisitely eco-luxurious.",
    descriptionBn: "চোখ জুড়ানো আকাশি/টার্কিশ ব্লু রঙের দুই স্তরের ডাবল ফ্লাওয়ার ড্রপ কানের দুল। প্রতিটি ফুলের ঠিক কেন্দ্রে রয়েছে গোল্ডেন বেজেলে বসানো দ্যুতিময় ফেসেটেড ক্রিস্টাল স্টোন। হাঁটাচলার সাথে সাথে দুলটির দুই স্তরের দোলন অত্যন্ত মার্জিত ও নান্দনিক দেখায়। আধুনিক পার্টি, ক্যাজুয়াল আউটফিট কিংবা বাঙালি ট্র্যাডিশনাল যেকোনো সাজে এটি এক অনন্য আকর্ষণ।",
    storyEn: "Engineered by our master jute artisans using micro-rope rolling techniques. The dual blossoms are linked with flexible metal eyelets to ensure dynamic sway and fluid motion.",
    storyBn: "পাটবাড়ির কারিগরদের নিখুঁত হাতে বোনা। দুটি ফুলকে সূক্ষ্ম লিংকের সাহায্যে যুক্ত করা হয়েছে যেন হাঁটার সময় কানের দুলটি স্বাভাবিক দোলাচল তৈরি করে আলো ছড়ায়।",
    featuresEn: [
      "Two-tier cascading dual-flower drop structure",
      "Faceted diamond-cut crystal rhinestones with gold-tone bezel setting",
      "Hand-rolled micro-jute cord petals with rich turquoise pigment",
      "Lightweight long drop (~16g per pair) with sterling-silver finish wire hooks",
      "Perfect statement piece for receptions, casual outings, and gifting"
    ],
    featuresBn: [
      "দুই স্তরের ঝুলন্ত ডাবল ফ্লাওয়ার ড্রপ ডিজাইন",
      "কেন্দ্রে আলো প্রতিফলিতকারী প্রিমিয়াম ফেসেটেড ক্রিস্টাল স্টোন",
      "টার্কিশ ব্লু রঙে রাঙানো মসৃণ মাইক্রো-জুট কয়েল ফিনিশ",
      "দীর্ঘ ঝুলন্ত লুক সত্ত্বেও ওজনে অত্যন্ত হালকা (১৬ গ্রাম/জোড়া)",
      "পার্টি, রিসেপশন, কলেজ-ভার্সিটি বা প্রিয়জনকে উপহার দেওয়ার জন্য সেরা"
    ],
    dimensionsEn: "Total Drop Length: 7.5 cm (3 in), Flower Diameter: 3.8 cm, Weight: 16g/pair",
    dimensionsBn: "মোট দৈর্ঘ্য: ৭.৫ সেমি, ফুলের ব্যাস: ৩.৮ সেমি, ওজন: ১৬ গ্রাম/জোড়া",
    materialEn: "Premium dyed jute thread, faceted crystal glass rhinestones, brass alloy findings",
    materialBn: "প্রিমিয়াম ডাইড পাটের সুতো, ফেসেটেড ক্রিস্টাল গ্লাস স্টোন, ব্রাস কানেক্টর ও হুক",
    careEn: [
      "Avoid direct water exposure and moisture; wipe metal hooks with dry cloth",
      "Store flat in the provided eco-pouch to maintain flower symmetry",
      "Handle gently by the hook when putting on and taking off"
    ],
    careBn: [
      "পানিতে ভেজাবেন না; আর্দ্রতা থেকে দূরে রাখুন এবং ব্যবহারের পর শুকনো কাপড়ে মুছে রাখুন",
      "ফুলের কুন্ডলীর গঠন অক্ষুণ্ণ রাখতে সমতলভাবে জুয়েলারি পাউচে সংরক্ষণ করুন",
      "পড়ার সময় সাবধানে হুক ধরে পরুন"
    ],
    primaryImage: "/images/products/jute-drop-earrings-cyan.jpg",
    images: [
      "/images/products/jute-drop-earrings-cyan.jpg",
      "/images/products/jute-drop-earrings-cyan-model.jpg",
      "/images/products/jute-drop-earrings-cyan-stand.jpg"
    ],
    badge: {
      text: "হাতে তৈরি",
      textEn: "Handmade",
      variant: "handmade"
    },
    isFeatured: true,
    inStock: true,
    rating: 5.0,
    reviewsCount: 29,
    variants: [
      { k: "single", en: "Single Pair", bn: "১ জোড়া", price: 380 },
      { k: "gift_duo", en: "Duo Gift Box (2 Pairs)", bn: "২ জোড়া গিফট বক্স", price: 720 },
    ],
  },
];

declare global {
  var __paatbari_products: Product[] | undefined;
}

if (!globalThis.__paatbari_products) {
  globalThis.__paatbari_products = JSON.parse(JSON.stringify(PRODUCTS));
}

export const catalogStore = {
  getAll: (): Product[] => PRODUCTS,
  getBySlug: (slug: string): Product | undefined =>
    PRODUCTS.find((p) => p.slug === slug),
  getById: (id: string): Product | undefined =>
    PRODUCTS.find((p) => p.id === id),
  updateVariantPrice: (productId: string, variantKey: string, newPrice: number): boolean => {
    const p = PRODUCTS.find((prod) => prod.id === productId);
    if (!p) return false;
    const v = p.variants.find((v) => v.k === variantKey);
    if (!v) return false;
    v.price = newPrice;
    return true;
  },
  toggleStock: (productId: string): boolean => {
    const p = PRODUCTS.find((prod) => prod.id === productId);
    if (!p) return false;
    p.inStock = p.inStock === false ? true : false;
    return true;
  },
  reset: () => {
    // reset to original
  },
};

export const BUNDLE_PROMO = {
  id: "BN1",
  en: "Eco Home Living Master Bundle",
  bn: "ইকো হোম লিভিং মাস্টার বান্ডেল",
  itemsTextEn: "2 Cushion Covers (16x16) + 1 Table Runner (14x72) + 1 Set Placemats (6pcs)",
  itemsTextBn: "২টি কুশন কভার (১৬×১৬) + ১টি টেবিল রানার (১৪×৭২) + ১ সেট প্লেসম্যাট (৬টি)",
  itemsText: "২টি কুশন কভার + ১টি টেবিল রানার + ১ সেট প্লেসম্যাট (৬টি)",
  originalPrice: 1800,
  discountPct: 15,
  bundlePrice: 1530,
};
