"use client";

import React, { useState } from "react";
import { useLanguage } from "@/lib/i18n-context";
import {
  Leaf,
  Sparkles,
  TrendingUp,
  Droplets,
  HeartHandshake,
  ShieldCheck,
  Globe2,
  Share2,
  MessageCircle,
} from "lucide-react";

export interface EcoImpactCalculatorProps {
  initialUnits?: number;
  className?: string;
  isB2B?: boolean;
}

export function EcoImpactCalculator({
  initialUnits = 50,
  className = "",
  isB2B = false,
}: EcoImpactCalculatorProps) {
  const { locale, toLocaleDigits } = useLanguage();
  const [units, setUnits] = useState(initialUnits);

  // Scientific impact formulas (based on FAO & Bangladesh Jute Research Institute data)
  // 1 Jute product replaces 500 single-use polythene bags (~2.5 kg LDPE)
  const plasticBagsSaved = units * 500;
  const plasticKgSaved = (units * 2.5).toFixed(1);

  // 1 hectare of jute consumes 15 tons of CO2 in 100 days (~3.2 kg CO2 net absorbed per finished bag)
  const co2AbsorbedKg = (units * 3.2).toFixed(1);

  // Compared to polyester/synthetic PVC bags, jute saves ~2,700 liters of freshwater processing
  const waterSavedLiters = Math.round(units * 270);

  // Fair-wage livelihood work for Manikganj rural women artisans
  const artisanHours = (units * 3.5).toFixed(0);

  const presets = isB2B ? [100, 250, 500, 1000, 2500] : [5, 20, 50, 100, 250];

  return (
    <div
      className={`relative overflow-hidden bg-gradient-to-br from-forest via-[#194030] to-forest text-white rounded-3xl p-6 sm:p-10 shadow-2xl border border-jute/30 ${className}`}
    >
      {/* Background Ambient Eco Glows */}
      <div className="absolute -top-24 -right-24 w-80 h-80 bg-jute/15 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-24 -left-24 w-80 h-80 bg-leaf/20 rounded-full blur-3xl pointer-events-none" />

      <div className="relative z-10 space-y-8">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/15 pb-6">
          <div className="space-y-1">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-jute text-xs font-semibold border border-jute/30 mb-1">
              <Sparkles className="w-3.5 h-3.5 text-jute animate-pulse" />
              <span>
                {locale === "bn"
                  ? "লাইভ এআই সাসটেইনেবিলিটি ও কার্বন ট্র্যাকার"
                  : "Live ESG & Carbon Offset Tracker"}
              </span>
            </div>
            <h3 className="text-2xl sm:text-3xl font-bold font-bn-display text-white">
              {locale === "bn"
                ? "আপনার কেনাকাটায় পৃথিবীর লাভ কতটুকু?"
                : "Real-Time Environmental & Social Impact"}
            </h3>
            <p className="text-xs sm:text-sm text-sand/80 max-w-xl">
              {locale === "bn"
                ? "প্লাস্টিক ও সিন্থেটিকের বিপরীতে পাট বেছে নিয়ে আপনি পরিবেশ ও গ্রামীণ নারী কারিগরদের জীবনে কী পরিবর্তন আনছেন তা সরাসরি পরিমাপ করুন।"
                : "Measure the exact plastic pollution prevented, carbon sequestered, and rural women work hours generated by your purchase."}
            </p>
          </div>

          <div className="flex items-center gap-2 self-start sm:self-center">
            <span className="px-3 py-1.5 rounded-full bg-jute/20 border border-jute/40 text-jute text-xs font-bold flex items-center gap-1.5 shadow-xs">
              <Globe2 className="w-3.5 h-3.5" />
              <span>EU PPWR & ESG Ready</span>
            </span>
          </div>
        </div>

        {/* Interactive Slider Section */}
        <div className="space-y-4 bg-white/5 backdrop-blur-md p-5 sm:p-6 rounded-2xl border border-white/10">
          <div className="flex items-center justify-between">
            <label htmlFor="jute-units-slider" className="text-xs sm:text-sm font-semibold text-sand">
              {locale === "bn" ? "পাটজাত পণ্যের পরিমাণ নির্ধারণ করুন:" : "Select Quantity of Jute Products:"}
            </label>
            <div className="text-right">
              <span className="text-2xl sm:text-3xl font-extrabold text-jute font-mono">
                {locale === "bn" ? toLocaleDigits(units) : units}
              </span>
              <span className="text-xs text-white/70 ml-1.5">
                {locale === "bn" ? "টি পণ্য" : "Units"}
              </span>
            </div>
          </div>

          {/* Range Slider */}
          <input
            id="jute-units-slider"
            type="range"
            min={isB2B ? "50" : "1"}
            max={isB2B ? "5000" : "500"}
            step={isB2B ? "50" : "1"}
            value={units}
            onChange={(e) => setUnits(Number(e.target.value))}
            className="w-full h-2.5 bg-white/20 rounded-lg appearance-none cursor-pointer accent-jute focus:outline-none"
          />

          {/* Quick Preset Buttons */}
          <div className="flex items-center gap-2 pt-1 flex-wrap">
            <span className="text-[11px] text-white/60 mr-1">
              {locale === "bn" ? "কুইক সিলেকশন:" : "Presets:"}
            </span>
            {presets.map((p) => (
              <button
                key={p}
                type="button"
                onClick={() => setUnits(p)}
                className={`px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                  units === p
                    ? "bg-jute text-forest shadow-md scale-105"
                    : "bg-white/10 hover:bg-white/20 text-white/90"
                }`}
              >
                {locale === "bn" ? toLocaleDigits(p) : p} {locale === "bn" ? "পিস" : "pcs"}
              </button>
            ))}
          </div>
        </div>

        {/* 4 Impact Metric Cards */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {/* 1. Plastic Waste Prevented */}
          <div className="bg-white/10 backdrop-blur-md border border-white/15 rounded-2xl p-4 sm:p-5 flex flex-col justify-between hover:bg-white/15 transition-all">
            <div className="flex items-center justify-between text-clay mb-3">
              <span className="text-xl sm:text-2xl">🚫</span>
              <span className="text-[10px] font-bold tracking-wider uppercase bg-clay/30 text-white px-2 py-0.5 rounded-full">
                Zero Plastic
              </span>
            </div>
            <div>
              <div className="text-xl sm:text-3xl font-black text-white font-mono tracking-tight">
                {locale === "bn" ? toLocaleDigits(plasticBagsSaved.toLocaleString()) : plasticBagsSaved.toLocaleString()}
              </div>
              <span className="text-xs font-bold text-jute block mt-0.5">
                {locale === "bn" ? "টি পলিথিন রোধ" : "Polybags Replaced"}
              </span>
              <p className="text-[11px] text-white/60 mt-1 leading-snug">
                {locale === "bn"
                  ? `মোট প্রায় ${toLocaleDigits(plasticKgSaved)} কেজি অপচনশীল প্লাস্টিক বর্জ্য মাটি ও নদী থেকে রক্ষা পাবে।`
                  : `Prevents ~${plasticKgSaved} kg of non-degradable microplastic from landfills.`}
              </p>
            </div>
          </div>

          {/* 2. CO2 Absorbed */}
          <div className="bg-white/10 backdrop-blur-md border border-white/15 rounded-2xl p-4 sm:p-5 flex flex-col justify-between hover:bg-white/15 transition-all">
            <div className="flex items-center justify-between text-leaf mb-3">
              <span className="text-xl sm:text-2xl">🌱</span>
              <span className="text-[10px] font-bold tracking-wider uppercase bg-leaf/40 text-jute px-2 py-0.5 rounded-full">
                Carbon Sink
              </span>
            </div>
            <div>
              <div className="text-xl sm:text-3xl font-black text-white font-mono tracking-tight">
                {locale === "bn" ? toLocaleDigits(co2AbsorbedKg) : co2AbsorbedKg} <span className="text-sm font-normal">kg</span>
              </div>
              <span className="text-xs font-bold text-jute block mt-0.5">
                {locale === "bn" ? "কার্বন ডাইঅক্সাইড শোষিত" : "Net CO₂ Sequestered"}
              </span>
              <p className="text-[11px] text-white/60 mt-1 leading-snug">
                {locale === "bn"
                  ? "পাটগাছ ১০০ দিনের বৃদ্ধির সময়ে বিপুল পরিমাণ কার্বন শোষণ করে প্রচুর অক্সিজেন ছড়ায়।"
                  : "Natural photosynthetic carbon capture during Bangladesh jute crop growth."}
              </p>
            </div>
          </div>

          {/* 3. Water Conserved */}
          <div className="bg-white/10 backdrop-blur-md border border-white/15 rounded-2xl p-4 sm:p-5 flex flex-col justify-between hover:bg-white/15 transition-all">
            <div className="flex items-center justify-between text-cyan-300 mb-3">
              <span className="text-xl sm:text-2xl">💧</span>
              <span className="text-[10px] font-bold tracking-wider uppercase bg-cyan-500/30 text-cyan-200 px-2 py-0.5 rounded-full">
                Water Saver
              </span>
            </div>
            <div>
              <div className="text-xl sm:text-3xl font-black text-white font-mono tracking-tight">
                {locale === "bn" ? toLocaleDigits(waterSavedLiters.toLocaleString()) : waterSavedLiters.toLocaleString()} <span className="text-sm font-normal">L</span>
              </div>
              <span className="text-xs font-bold text-jute block mt-0.5">
                {locale === "bn" ? "লিটার বিশুদ্ধ পানি সাশ্রয়" : "Liters Water Saved"}
              </span>
              <p className="text-[11px] text-white/60 mt-1 leading-snug">
                {locale === "bn"
                  ? "সিন্থেটিক ফ্যাব্রিক বা লেদার প্রসেসিংয়ের তুলনায় পাটের পানি ফুটপ্রিন্ট অনেক কম।"
                  : "Versus petrochemical synthetics and water-intensive faux-leather tanning."}
              </p>
            </div>
          </div>

          {/* 4. Rural Women Livelihoods */}
          <div className="bg-white/10 backdrop-blur-md border border-white/15 rounded-2xl p-4 sm:p-5 flex flex-col justify-between hover:bg-white/15 transition-all">
            <div className="flex items-center justify-between text-amber-300 mb-3">
              <span className="text-xl sm:text-2xl">👩‍🌾</span>
              <span className="text-[10px] font-bold tracking-wider uppercase bg-amber-500/30 text-amber-200 px-2 py-0.5 rounded-full">
                Fair Wages
              </span>
            </div>
            <div>
              <div className="text-xl sm:text-3xl font-black text-white font-mono tracking-tight">
                {locale === "bn" ? toLocaleDigits(artisanHours) : artisanHours} <span className="text-sm font-normal">hrs</span>
              </div>
              <span className="text-xs font-bold text-jute block mt-0.5">
                {locale === "bn" ? "কারিগর সম্মানজনক কর্মঘণ্টা" : "Artisan Work Hours"}
              </span>
              <p className="text-[11px] text-white/60 mt-1 leading-snug">
                {locale === "bn"
                  ? "মানিকগঞ্জের গ্রামীণ নারী তাঁতি ও কারিগরদের ঘরে সরাসরি ন্যায্য পারিশ্রমিক পৌঁছায়।"
                  : "Direct livelihood support empowering rural women weavers in Manikganj Sadar."}
              </p>
            </div>
          </div>
        </div>

        {/* Footer Actions / ESG Inquiries */}
        <div className="pt-2 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-white/75 border-t border-white/10">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-jute" />
            <span>
              {locale === "bn"
                ? "জাতিসংঘের এসডিজি লক্ষ্যমাত্রা (SDG 12 ও 13) এবং সার্কুলার ইকোনমির সাথে সামঞ্জস্যপূর্ণ।"
                : "Aligned with UN Sustainable Development Goals (SDG 12 Responsible Consumption & SDG 13 Climate Action)."}
            </span>
          </div>

          <a
            href={`https://wa.me/8801793648214?text=${encodeURIComponent(
              locale === "bn"
                ? `হ্যালো পাটবাড়ি, আমরা ${units} টি পাটজাত পণ্যের করপোরেট/পাইকারি পরিবেশবান্ধব ইমপ্যাক্ট অর্ডার ও কোটেশন আলোচনা করতে আগ্রহী।`
                : `Hello Paatbari, we are interested in discussing an eco-friendly B2B corporate order of ${units} units with ESG metrics.`
            )}`}
            target="_blank"
            rel="noopener noreferrer"
            className="px-4 py-2.5 rounded-xl bg-jute text-forest font-bold hover:bg-jute/90 hover:scale-105 active:scale-95 transition-all flex items-center gap-2 flex-shrink-0 shadow-lg"
          >
            <MessageCircle className="w-4 h-4 fill-current" />
            <span>
              {locale === "bn" ? "ইকো ইমপ্যাক্ট অর্ডার ও কোটেশন" : "Request Custom ESG Quote"}
            </span>
          </a>
        </div>
      </div>
    </div>
  );
}
